### PR TITLE
Setup and basics

### PR DESCRIPTION
**Pull request by OliverWarrington**
Hey Tim, 

Could you have a look to see if you're happy with the changes? Please suggest any edits etc! 

- [x] I added a setup section talking about how to start a project from a repo. Not sure what to put on the intro page and I might have missed some features/details that you would know about. 

- [x] Are you happy with the first 4 pages of the basics?

### CODE REVIEW

**Review by TimVanMourik — COMMENTED** [review]
Thanks for the docs update @OliverWarrington!

* I really like the setup and getting-started part! I might make some changes 
* I will write a bit about the different animals... I haven't quite decided whether or not to get rid of them or not. 
* After user requests I just moved the "Delete node" button up into the parameter editor. For the documentation that's actually quite useful because that way it fits into the picture. On that same picture:
  * "Change visibility in workflow editor" --> "Toggle visibility in workflow editor"
  * "Iterate" --> "Iterate over this parameter" (maybe a link to the respective page in the caption)
  * "Delete" --> "Remove this parameter from the node"

I made minor textual edits in two commits. If you could update the picture, that would be great! For the, looking perfect and ready to merge!  🙂 🎉

**Comment by OliverWarrington** [comment]
Hey @TimVanMourik,

Finally made the changes to the image you mentioned! 

I also added a button to navigate back to the list of documentation pages from each page, just something I wanted while working on them. I think I've probably added it to the wrong place (_includes/post_pagination.html) and it could definitely look better on the page, so please feel free to tell me what the proper implementation should be 😄

**Comment by TimVanMourik** [comment]
Brilliant, thanks! I'm on holiday this week but I'll try look at this as soon as I'm back!

**Comment by TimVanMourik** [comment]
Thanks @OliverWarrington!
I like you "Index" in the navigation suggestion. In the commit above (8b290f68ccf957f97df767fd0f7d3ce828e1e161) I made small changes in layout:
* I would like all three buttons (previous, index, next) next to each other. I therefore changed their layout in the `navigation.scss` file. The size is reduced from 50% to 30%.
* Some small additional changes to make the boxes look prettier
* the `page.index` does not actually exist so it's redundant in the if statement. But it doesn't need an if anyway as every page could link to the index. 
* I moved the button to in between the other two.

**Pull request merged**
